enum CLASSPROCESS {
  MAIN = 'MAIN',
  PROVISIONAL_EXECUTION = 'PROVISIONAL_EXECUTION',
}
enum STAGEPROCESS {
  ANALISE = 'ANALISE',
  PRE_ANALISE = 'PRE_ANALISE',
  CALCULO = 'CALCULO',
}

const StageByCode: Record<number, STAGEPROCESS> = {
  781: STAGEPROCESS.PRE_ANALISE,
  779: STAGEPROCESS.PRE_ANALISE,
  777: STAGEPROCESS.PRE_ANALISE,
  802: STAGEPROCESS.PRE_ANALISE,
  769: STAGEPROCESS.ANALISE,
  762: STAGEPROCESS.ANALISE,
  755: STAGEPROCESS.ANALISE,
  787: STAGEPROCESS.ANALISE,
  770: STAGEPROCESS.CALCULO,
  763: STAGEPROCESS.CALCULO,
  756: STAGEPROCESS.CALCULO,
  797: STAGEPROCESS.CALCULO,
};
enum TypeActivity {
  PRE_ANALISE = 'PRE_ANALISE',
  ANALISE = 'ANALISE',
  CALCULO = 'CALCULO',
}

enum ActivityStatus {
  LOSS = 'LOSS',
  APROVED = 'APROVED',
}

export {
  CLASSPROCESS,
  STAGEPROCESS,
  StageByCode,
  TypeActivity,
  ActivityStatus,
};
