export enum PROCESSSTATUSENUM {
  PROCESSING_WITH_MOVIMENTS = 'PROCESSING_WITH_MOVIMENTS',
  PROCESSING_WITH_DOCUMENTS = 'PROCESSING_WITH_DOCUMENTS',
  PROCESS_WAITING_EXTRACTION_DOCUMENTS = 'PROCESS_WAITING_EXTRACTION_DOCUMENTS',
  EXTRACTION_MOVIMENTS_FINISHED = 'EXTRACTION_MOVIMENTS_FINISHED',
  EXTRACTION_DOCUMENTS_FINISHED = 'EXTRACTION_DOCUMENTS_FINISHED',
}
