enum PreAnaliseStatus {
  ARQUIVADO = 'PRÉ-ANÁLISE – ARQUIVADO',
  CLASSE_INELEGIVEL = 'PRÉ-ANÁLISE – CLASSE INELEGÍVEL',
  LISTA_EMPRESA_INELEGIVEL = 'PRÉ-ANÁLISE – LISTA DE EMPRESA INELEGÍVEL',
  NAO_E_TRABALHISTA = 'PRÉ-ANÁLISE – NÃO É TRABALHISTA',
  PROCESSO_FISICO = 'PRÉ-ANÁLISE – PROCESSO FÍSICO',
  SEGREDO_JUSTICA = 'PRÉ-ANÁLISE – SEGREDO DE JUSTIÇA',
  SEM_ACORDAO = 'PRÉ-ANÁLISE – SEM ACÓRDÃO',
  IMPROCEDENTE = 'PRÉ-ANÁLISE – IMPROCEDENTE',
}
enum AnaliseStatus {
  AGUARDAR_TRANSITO = 'ANÁLISE – AGUARDAR TRÂNSITO',
  TRT_INACESSIVEL = 'ANÁLISE - FALHA AO TENTAR ACESSAR INFORMAÇÕES, TENTE NOVAMENTE MAIS TARDE',
  AGUARDAR_DECISAO_TST = 'ANÁLISE – AGUARDAR DECISÃO DO TST',
  ABAIXO_VALOR_MINIMO = 'ANÁLISE – ABAIXO DO VALOR MÍNIMO',
  IMPROCEDENTE = 'ANÁLISE – IMPROCEDENTE',
  LIQUIDADO = 'ANÁLISE – LIQUIDADO',
  RISCO_TESE = 'ANÁLISE – RISCO DE TESE',
  RISCO_PRAZO = 'ANÁLISE – RISCO DE PRAZO',
  RISCO_TESE_PENDENTE_TRANSITO = 'ANÁLISE – RISCO DE TESE – PENDENTE TRÂNSITO EM JULGADO',
  //TODO-VALIDAR STATUS PROCESSO_PRINCIPAL_ARQUIVADO_SEM_PROVISORIA
  PROCESSO_PRINCIPAL_ARQUIVADO_SEM_PROVISORIA = 'ANÁLISE – PROCESSO PRINCIPAL ARQUIVADO E NÃO EXISTE EXECUÇÃO PROVISÓRIA',
  EXECUCAO_PROVISORIA_ARQUIVADO_SEM_PRINCIPAL = 'ANÁLISE – EXECUÇÃO PROVISÓRIA ARQUIVADO E NÃO EXISTE PROCESSO PRINCIPAL',
  PROCESSOS_ARQUIVADOS = 'ANÁLISE – EXECUÇÃO PROVISÓRIA E PROCESSO PRINCIPAL ARQUIVADOS',
  PROCESSO_SEM_CREDITO = 'ANÁLISE – PROCESSO SEM CREDITO',
}
export { PreAnaliseStatus, AnaliseStatus };
